### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sachinshilwal** [tadejf84/js-range-slider#2]
Hi, I can't make this circular slider run. I have applied everything according to docs, yet not work and console prints out following error:
![image](https://user-images.githubusercontent.com/34100453/185742031-45412530-6ec6-4ba4-bac7-20bfa8024f78.png)

**Comment by tadejf84** [comment]
Hey @sachinbro ! Thanks for your message! I've commited a new change which an additional check if TouchEvent exists in the browser first: if( window.TouchEvent && e instanceof TouchEvent ) ...

It was working in Chrome before, but it broke in Firefox for example. It should be working fine now. Please pull again and let me know if it works for you now.

**Comment by sachinshilwal** [comment]
Thank you for such quick update. You are the best man.
